---
pipeline_elements:
    - description: "definition of which pipeline elements to run for this config"
      directory: "./scripts"
      elements:
        - description: "get configuration from gitlab"
          script: "config_retrieve.sh"
          enabled: true
      

datastores:
    - description: "top level local datastore"
      local_dir: "./source_datastore"
      remote_dir: 
      symbolic: false
    
    - description: "satellite local datastore"
      local_dir: "./source_datastore/satellite"
      remote_dir: 
      symbolic: false
    
    - description: "drone local datastore"
      local_dir: "./source_datastore/drone"
      remote_dir: 
      symbolic: false
    
    - description: "satellite local annotations"
      local_dir: "./source_datastore/satellite/annotations"
      remote_dir: 
      symbolic: false
    
    - description: "drone local annotations"
      local_dir: "./source_datastore/drone/annotations"
      remote_dir: 
      symbolic: false
    
    - description: "source DPLUS214 satellite imagery datastore"
      local_dir: "./source_datastore/satellite/DPLUS214_Elephant_Seals/"
      remote_dir: "/data/magic/datasets/remotesensing/vhr/DPLUS214_Elephant_Seals/"
      symbolic: true
    
    - description: "source DPLUS109 satellite imagery datastore"
      local_dir: "./source_datastore/satellite/DPLUS109_Archive_Images/"
      remote_dir: "/data/magic/datasets/remotesensing/vhr/DarwinPlus/"
      symbolic: true
    
    - description: "satellite annotations"
      local_dir: "./source_datastore/satellite/annotations/DPLUS109_annotations/"
      remote_dir: "/data/wfs/darwin-elephant-seal/datastore/annotations/DPLUS109_annotations/"
      symbolic: true
    
    - description: "drone annotations"
      local_dir: "./source_datastore/drone/annotations/DPLUS214_drone_annotations/"
      remote_dir: "/data/wfs/darwin-elephant-seal/datastore/annotations/DPLUS214_drone_annotations/"
      symbolic: true
    
    - description: "source drone imagery datastore"
      local_dir: "./source_datastore/drone/DPLUS214_drone_imagery/"
      remote_dir: "/data/wfs/darwin-elephant-seal/datastore/DPLUS214_drone_imagery/"
      symbolic: true
    
    - description: "source aois"
      local_dir: "./source_datastore/aois/"
      remote_dir: "/data/wfs/darwin-elephant-seal/datastore/aois/"
      symbolic: true
    
    - description: "cached datastore"
      local_dir: "./cached_datastore"
      remote_dir: 
      symbolic: false
    
    - description: "tiles cached datastore"
      local_dir: "./cached_datastore/tiles"
      remote_dir: 
      symbolic: false
    
    - description: "drone tiles cached datastore"
      local_dir: "./cached_datastore/drone_tiles"
      remote_dir: 
      symbolic: false
    
    - description: "satellite tiles cached datastore"
      local_dir: "./cached_datastore/satellite_tiles"
      remote_dir: 
      symbolic: false

    - description: "pngs cached datastore"
      local_dir: "./cached_datastore/pngs"
      remote_dir: 
      symbolic: false
    
    - description: "results datastore"
      local_dir: "./results_datastore"
      remote_dir: 
      symbolic: false


images:
    - source_dir: "./source_datastore/satellite/DPLUS214_Elephant_Seals/"
      dest_dir: "./cached_datastore"
      sources:
          - dir: "dg_104001009E9C4C00_SG_Hound_Bay/016418161040_01_P001_MUL"
            format: mul
            type: satellite
            labels: ""
            files:
              - "24NOV06121904-M2AS_R1C1-016418161040_01_P001.TIF"
            symbolic: false

          - dir: "dg_104001009E9C4C00_SG_Hound_Bay/016418161040_01_P001_PAN"
            format: pan
            type: satellite
            labels: ""
            files:
              - "24NOV06121904-P2AS_R1C1-016418161040_01_P001.TIF"
            symbolic: false

    - source_dir: "./source_datastore/satellite/DPLUS109_Archive_Images/"
      dest_dir: "./cached_datastore"
      sources:
          - dir: "dg_1030010007208000_StAndrewsBay/015650812040_01_P002_PAN"
            format: pan
            type: satellite
            labels: "dg_1030010007208000_StAndrewsBay.shp"
            files:
              - "10OCT22123200-P2AS-015650812040_01_P002.TIF"
            symbolic: false
    
    - source_dir: "./source_datastore/drone/DPLUS214_drone_imagery/"
      dest_dir: "./cached_datastore"
      sources:
          - dir: "st_andrews_bay/Pix4D/IX-12-61425_0091/3_dsm_ortho/2_mosaic"
            format: mul
            type: drone
            labels: "Females-011124-61425_0091.shp"
            files:
              - "IX-12-61425_0091_mosaic_group1.tif"
            symbolic: false

annotations:
    - source_dir: "./source_datastore/drone/annotations/DPLUS214_drone_annotations/"
      dest_dir: "./cached_datastore"
      sources:
          - dir: "st_andrews_bay/011124"
            format: shp
            type: drone
            labels: ""
            files:
              - "Females-011124-61425_0091.*"
            symbolic: false
    
    - source_dir: "./source_datastore/satellite/annotations/"
      dest_dir: "./cached_datastore"
      sources:
          - dir: "DPLUS109_annotations"
            format: shp
            type: satellite
            labels: ""
            files:
              - "dg_1030010007208000_StAndrewsBay.*"
            symbolic: false

aois:
    - source_dir: "./source_datastore/"
      dest_dir: "./cached_datastore"
      sources:
          - dir: "aois"
            files:
              - "beach_aois.*"
            symbolic: false

